name: Lint and Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build:
    name: Build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: go run cmd/auth/main.go
        environment:
          - ENV
          - SECRET
          - AES
          - GODOTENV
          - FIBER_PREFORK
          - MAX_CPU
          - LOG_OUTPUT
          - LOG_LEVEL
          - LOG_FILE
          - LOG_CW
          - SENTRY_DSN
          - SENTRY_TSR
          - HOST
          - SECURE_COOKIE
          - DB_NAME
          - DB_HOST
          - DB_PORT
          - DB_USER
          - DB_PASSWORD
          - DB_SSLMODE
          - TTL_ACCESS
          - TTL_REFRESH
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Auth.json" --integration-id "128430-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint --integration-id 128430
